name: bubble_bottom_bar
description: Custom bottom bar widget for your app
version: 2.0.0
homepage: https://github.com/yourname/bubble_bottom_bar
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.3