// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_xHeb-n9uofwMx6B2ETrUQ8-nU3lxGg',
    appId: '1:690680283978:web:5d2b0599a7ef196e7537b3',
    messagingSenderId: '690680283978',
    projectId: 'getjobs-cbaea',
    authDomain: 'getjobs-cbaea.firebaseapp.com',
    storageBucket: 'getjobs-cbaea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Q52yNC2Zc0ijMCTzR0iLsc3p9rD3Ago',
    appId: '1:690680283978:android:486abc2f1e2ab60f7537b3',
    messagingSenderId: '690680283978',
    projectId: 'getjobs-cbaea',
    storageBucket: 'getjobs-cbaea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC228QMysbfxRtRMBEttGo6iM-j8O9TTZY',
    appId: '1:690680283978:ios:700bee816d3347db7537b3',
    messagingSenderId: '690680283978',
    projectId: 'getjobs-cbaea',
    storageBucket: 'getjobs-cbaea.firebasestorage.app',
    iosBundleId: 'com.example.getjobsFreelanceAppMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC228QMysbfxRtRMBEttGo6iM-j8O9TTZY',
    appId: '1:690680283978:ios:700bee816d3347db7537b3',
    messagingSenderId: '690680283978',
    projectId: 'getjobs-cbaea',
    storageBucket: 'getjobs-cbaea.firebasestorage.app',
    iosBundleId: 'com.example.getjobsFreelanceAppMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_xHeb-n9uofwMx6B2ETrUQ8-nU3lxGg',
    appId: '1:690680283978:web:beb3f10b3f8527b17537b3',
    messagingSenderId: '690680283978',
    projectId: 'getjobs-cbaea',
    authDomain: 'getjobs-cbaea.firebaseapp.com',
    storageBucket: 'getjobs-cbaea.firebasestorage.app',
  );
}
